/// Flutter icons Construction
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Construction
///      fonts:
///       - asset: fonts/Construction.ttf
///
/// 
/// * RPG Awesome, Copyright (c) 2014, Daniela Howe
///         Author:    Daniela Howe & Ivan Montiel
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://nagoshiashumari.github.io/Rpg-Awesome/
///
import 'package:flutter/widgets.dart';

class Construction {
  Construction._();

  static const _kFontFam = 'Construction';
  static const _kFontPkg = null;

  static const IconData shovel = IconData(0xea9b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
